name: Sample Workflow
on:
  push:
    branches: [ FeatureBranch1 ]
    paths:
            - 'force-app/**'        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the source code
    - name: 'Checkout source code'
      uses: actions/checkout@v2

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core

    - name: 'Populate auth file with SFDX_URL secret'
      shell: bash
      run: 'echo ${{ secrets.SFDX_LR_TEST_URL}} > SFDX_QA'

    - name: 'Authenticate against dev hub'
      run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_QA -s -a LRQA
        
    - name: Run Apex test
      run: 
        node_modules/sfdx-cli/bin/run force:apex:test:run --resultformat tap --codecoverage -c -r human
        
    - name: Deploy source
      id: Deploy
      if: github.event_name == 'push'
      run:
        node_modules/sfdx-cli/bin/run force:source:deploy -p diffdeploy/force-app -u LRQA --json --loglevel fatal
